### ISSUE TITLE
Objets célestes

### ISSUE THREAD

**Issue by Antoniatch** [WildCodeSchool/tlse0921-js-p2-Espacito#58]
Ce serait cool que quand on appuie sur "astéroïdes suivantes" ça nous renvoie en haut de la page, pour que la navigation soit plus agréable. Sinon on part d'en bas, et on doit remonter pour voir les cards, puis redescendre pour cliquer encore sur "suivant" :)

**Comment by emmanouti** [comment]
en version desktop il y a des retours à la ligne mal placé notamment pour la date, "potentiellement dangereux" il manque un 'n', enlever l'accent à "estimé", un '.' à seulement kilomètres

**Comment by cyrcab** [comment]
Je chipote mais je mettrai bien un cursor pointer sur les boutons pour changer d'objet céleste 🤡
